### ISSUE TITLE
Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by PauloFurtunatoAlexandre** [rafaelcmrj/bot-btc-poloniex#1]
at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/gigaP/Desktop/bot-bit-poloniex/index.js:5:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by rafaelcmrj** [comment]
npm install request

_Rafael Costa ._ _Sócio - Diretor_
Cel: +1 (385) 321-7393
E-mail: rafaelcosta@afigueira.com.br
..........................................................................
_www.afigueira.com.br http://www.afigueira.com.br_

**Comment by PauloFurtunatoAlexandre** [comment]
installed.
