### ISSUE TITLE
TypeError: Cannot read property 'binary' of undefined at WebSocket.<anonymous>

### ISSUE THREAD

**Issue by wholeeoh** [rafaelcmrj/bot-btc-poloniex#8]
Hey there, appreciate the work you've done on this. Hopefully you can help. I really want to test it out but keep getting this error:

`TypeError: Cannot read property 'binary' of undefined at WebSocket.<anonymous> (C:\Users\my_username\Desktop\bot-btc-poloniex\node_modules\autobahn\lib\transport\websocket.js:99:22)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at Receiver._receiver.onmessage (C:\Users\my_username\Desktop\bot-btc-poloniex\node_modules\ws\lib\WebSocket.js:146:47)
    at Receiver.dataMessage (C:\Users\my_username\Desktop\bot-btc-poloniex\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (C:\Users\my_username\Desktop\bot-btc-poloniex\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (C:\Users\my_username\Desktop\bot-btc-poloniex\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (C:\Users\my_username\Desktop\bot-btc-poloniex\node_modules\ws\lib\Receiver.js:139:10)
    at TLSSocket._ultron.on (C:\Users\my_username\Desktop\bot-btc-poloniex\node_modules\ws\lib\WebSocket.js:142:22)
    at emitOne (events.js:96:13)
`

**Comment by wholeeoh** [comment]
If anyone else runs into this issue, visit https://github.com/websockets/ws/commit/c15118f0636d81497db9ad34663efc98b9ddc9c3#diff-ee39beab4c8223a58e34e180ba59f345

undo all the changes they made to the 'flags' argument. May be another solution, but that's the way I was able to figure it out. 😆
